### PR TITLE
solved issue #23 added the main netflix home page

### PR DESCRIPTION
**Pull request by 123shreyanvi**
Screenshot 2024-01-04 191536
Screenshot 2024-01-04 191518
Screenshot 2024-01-04 191419

Screenshot 2024-01-04 19144
![Screenshot 2024-01-04 191419
9](https://github.com/rohit32999/Netflix-Sign-In-Page/assets/110835200/2c783925-d809-4cb2-8cac-96509ca09015)
 added some animation on scroll

### CODE REVIEW

**Comment by 123shreyanvi** [comment]
@Debaditya-Som Please do review this PR

**Comment by Debaditya-Som** [comment]
> @Debaditya-Som Please do review this PR

yep i'm reviewing it

**Comment by Debaditya-Som** [comment]
Nice one.. very impressive :)

**Comment by 123shreyanvi** [comment]
> Nice one.. very impressive :)

thankyou !!

**Pull request merged**
